spring:
  application:
    name: max-auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

max:
  jwt:
    issuer: "In5pEr"
    secretKey: "J0FagXWWKG0D1rWee4INxgypjWjEWXqMj33c5AZumnPsoF8QRLjxfC5bgKoK5uHqNmSffMjm2qQXMghW4ju4zrMxAx9Dlpq83HGgo05H8QEuue"
    duration: 31536000000 # 365 days in miliseconds


management:
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: ['*', 'prometheus']